### ISSUE TITLE
Image Resizing Options Not Available 

### ISSUE THREAD

**Issue by BharatSoni-BTC** [michelson/Dante#144] opened 2016-10-12 09:47 UTC
When we upload any image, There are some alignment options comes for aligning the image to user preference. I was looking for the same functions along with resizing image as well as Drag and Drop facility of moving images to one paragraph to another.

I would like If you can add that enhancement with the editor. I have attached the screenshot, Where the WordPress providing the same functionality along with the image alignment options.

![resize-image](https://cloud.githubusercontent.com/assets/17981135/19305518/e783adee-908e-11e6-9388-b921d28591e0.png)

**Comment by michelson** [comment] 2016-10-12 14:02
Hi @BharatSoni-BTC,
This is not enabled by design because you empower users to mess up the presentation of your page.
Less options == more control 💃

**Comment by creativeprogramming** [comment] 2016-10-13 01:08
resizing is also a bit nonsense in the age of responsive design

**Comment by BharatSoni-BTC** [comment] 2016-10-13 05:39
@michelson I am using Dante editor If you can suggest me which resize JavaScript will work along with the features of the Dante editor that would be very helpful.

**Comment by michelson** [comment] 2016-10-13 13:54
Hi @BharatSoni-BTC , I really don't know which resize library would help, because by design Dante will not allow image resizing. But It should be easy to hack on Dante and make image resize, but I really don't recommend that because enable that will break some expected behaviour on the editor.
I'm going to close this as is a no go.

best

**Closed by michelson** 2016-10-13 13:54 UTC

**Comment by BharatSoni-BTC** [comment] 2016-10-14 13:27
@michelson Thanks :+1:
